export const FontsList = [
    // 'Alfa Slab One',
    // 'Amatic SC',
    // 'Bad Script',
    // 'BenchNine',
    // 'Biryani',
    // 'Black Ops One',
    // 'Bungee Shade',
    // 'Changa One',
    // 'Cinzel',
    // 'Comfortaa',
    // 'Courier Prime',
    // 'Covered By Your Grace',
    // 'Crafty Girls',
    // 'Cutive',
    // 'Dancing Script',
    // 'Fjalla One',
    // 'Fredericka the Great',
    // 'Fredoka One',
    // 'Graduate',
    // 'Grand Hotel',
    // 'Great Vibes',
    // 'Homemade Apple',
    // 'Indie Flower',
    // 'Josefin Sans',
    // 'League Script',
    // 'Limelight',
    // 'Lobster',
    // 'Lora',
    // 'Love Ya Like A Sister',
    // 'Metal Mania',
    // 'Miss Fajardose',
    // 'Modak',
    // 'Monoton',
    // 'Montserrat',
    // 'Mouse Memoirs',
    // 'Mrs Saint Delafield',
    // 'Open Sans',
    // 'PT Serif',
    // 'Pacifico',
    // 'Parisienne',
    // 'Permanent Marker',
    // 'Pinyon Script',
    // 'Press Start 2P',
    // 'Raleway',
    // 'Rampart One',
    // 'Roboto Condensed',
    // 'Sacramento',
    // 'Slackey',
    // 'Sniglet',
    // 'Sofia',
    // 'Sorts Mill Goudy',
    // 'Spicy Rice',
    // 'Raleway',
    'Reem Kufi',
    'Noto Naskh Arabic',
    'Qahiri',
    'DroidNaskh-Regular',
    'A Thuluth Regular'
    
]
